### ISSUE TITLE
README and generalities

### ISSUE THREAD

**Issue by massimo-nocentini** [nobleVine/tesi-magistrale#1]
Hi guys,

write a `README.md` first of all. I've cloned your repo and figured out what's going on by skimming in the directory, I imagine that `index.html` should be the starting point. In spite of this, I think that writing it first allows us to proceed one step at a time to have a coherent environment at the end and, in the meantime, this workflow should be enhanced and described within the final thesis. I try to explain that better: 

- use the README to introduce the project and the main idea on which it lies; not a full documentation but short sentences that remark why you believe it interesting. Keep it updated with references to anything that is correlated somehow;
- then, describe dependencies necessary for your work (lots of them in the `libraries` folder).
- Finally, take care of you take under version control. Both the `__pycache__` folder and the `GlobalJSON.json` file have to be ignored; btw, you should explain how to rebuilt the latter using the `py_convert.py` script.

As a general "code of conduct" I propose to open a new issue both for reporting bugs, discuss difficulties and *to write down an idea to be developed/discussed later*, a kind of placeholder (a good reading should be https://opensource.guide/best-practices/ in general).

Cheers,
-massimo

**Comment by nobleVine** [comment]
Hi Massimo,

Thank you very much, the first version of the file README.md is done. We'll update the file during the course of the project.

Cheers,
Marco and Lorenzo
